### ISSUE TITLE
HTML 4.01以下 + Shift-JIS なサイトをプレビューしようとすると文字化けする

### ISSUE THREAD

**Issue by nexryai** [nexryai/summergo#1]
HTML 4.01までは、charset属性は規定されていないらしく  
https://github.com/nexryai/summergo/blob/10f0dd20a53192f70e04c0f4887356041340f57f/charset.go#L10-L23

で判別できない。

**Comment by nexryai** [comment]
[このサイト](https://www.clas.kitasato-u.ac.jp/~ogawa/C/C01.html) とか

**Comment by nexryai** [comment]
utf8かどうかを確認するのがベストなんだろうけどパフォーマンスに影響するんじゃないかというお気持ちがある（タイトルとかだけ見る分にはそこまで影響しない？）

**Comment by nexryai** [comment]
そもそもmeta見るためにanalyzeNodeでfor回しまくってる現状もパフォーマンス的に良いとは言えないかもしれないのでベンチマークなりで確認する必要がある

**Comment by nexryai** [comment]
レスポンスのContent-Typeヘッダーで明示してるならそれを使う → わからないならmetaを見る or タイトルがutf8か調べる  
で良さそう

**Comment by syobocat** [comment]
FYI: https://github.com/saintfish/chardet

**Comment by syobocat** [comment]
FYIそのに: https://github.com/goark/gnkf
